name: Deploy to GitHub Container Registry

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to GitHub Container Registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get Github tag
        id: meta
        run: |
          echo "::set-output name=tag::$(git describe --always --tags --match='v*')"
          
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}
          
      - name: Build and push id
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          file: Dockerfile
          tags: |
            ghcr.io/${{ github.actor }}/id:${{ steps.meta.outputs.tag }}
            
      #- name: Build and push Docker image
      #  uses: docker/build-push-action@v3
      #  with:
      #    username: ${{ github.actor }}
      #    password: ${{ secrets.CR_PAT }}
      #    registry: ghcr.io
      #    repository: ${{ github.repository }}
      #    tag_with_ref: true
      #    add_git_labels: true
      #    always_pull: true
      #    push: ${{ startsWith(github.ref, 'refs/tags/') }}
